<?php

namespace App\Filament\Resources\JobOrders\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class JobOrderInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('code')
                    ->columnSpanFull(),
                TextEntry::make('summary')
                    ->columnSpanFull(),
                TextEntry::make('target_date')
                    ->dateTime(),
                TextEntry::make('target_end')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('client.name')
                    ->label('Client')
                    ->placeholder('-'),
                TextEntry::make('address.id')
                    ->label('Address')
                    ->placeholder('-'),
                TextEntry::make('site_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('job_order_type'),
                TextEntry::make('status'),
                TextEntry::make('created_by')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('reviewed_by')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('sa_uploaded_by')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('jobable_type'),
                TextEntry::make('jobable_id')
                    ->numeric(),
                TextEntry::make('approved')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('reviewed')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pre_service_notes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('review')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('dept_head_review')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('rating')
                    ->placeholder('-'),
                TextEntry::make('dept_head_rating')
                    ->placeholder('-'),
                TextEntry::make('service_acknowledgement')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('signature')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('addpest')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('endorsed_files')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('endorsed_jo_hard_copy')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('endorsed_sa')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('endorsed_layout')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('tech_call_received')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('upsell')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('approved_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('reviewed_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
