<?php

namespace App\Filament\Widgets;

use App\Models\Lead;
use Filament\Widgets\StatsOverviewWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;
use Illuminate\Support\HtmlString;

class InquiryOverview extends StatsOverviewWidget
{
    protected function getStats(): array
    {
        return [
            Stat::make('Today', Lead::where('created_at', '>=', now()->startOfDay())->count()),
            Stat::make('This week',
                Lead::whereBetween('created_at', [now()->startOfWeek(), now()->endOfWeek()])->count()
            ),
            Stat::make('This month',
                Lead::whereBetween('created_at', [now()->startOfMonth(), now()->endOfMonth()])->count()
            ),
            Stat::make('This quarter',
                Lead::whereBetween('created_at', [now()->startOfQuarter(), now()->endOfQuarter()])->count()
            ),
            Stat::make('This year',
                Lead::whereBetween('created_at', [now()->startOfYear(), now()->endOfYear()])->count()
            ),
        ];
    }

    protected function getHeading(): ?string
    {
        return "Recieved Inquiries"; // TODO: Change the autogenerated stub
    }

    /**
     * @return array|int|null
     */
    public function getColumns(): int|array|null
    {
        return 5;
    }
}
