<?php

namespace App\Filament\Pages;

use App\Filament\Widgets\InquiryOverview;
use Filament\Pages\Dashboard as BaseDashboard;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Carbon;

class Dashboard extends BaseDashboard
{
    protected static bool $shouldRegisterNavigation = false;

    public function getSubheading(): string|Htmlable|null
    {
        return Carbon::today()->toFormattedDayDateString();
    }
    public static function shouldRegisterNavigation(): bool
    {
        return !auth()->user()->hasRole('technician');
    }

    public function getWidgets(): array
    {
        return [
            InquiryOverview::class,
        ];
    }

    public function getWidgetsSchemaComponents(array $widgets, array $data = []): array
    {
        return parent::getWidgetsSchemaComponents($widgets, $data); // TODO: Change the autogenerated stub
    }
}

